# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

scripts: &scripts
    - yarn install
    - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
    - |
        # build Android
        cd android
        ENVFILE=$ENV_SPECIFIC_FILE ./gradlew assembleRelease

COMMON_VARS: &COMMON_VARS
    XCODE_WORKSPACE: "TestProject"
    XCODE_SCHEME: "TestProject (staging)"
    APP_CENTER_TOKEN: Encrypted(Z0FBQUFBQmdXeWpMMUd3RndvZDN4LVZ2S0czWjJucnJzU3VPMFBPRVVoTE1kckhmdGlfLWpRazViQzFBT1VhM0l5Z2ZMZ29YMmxyc2pwMG9sNjZOV3F2ZGw5Mkw0UmVvRExtNVNMLWtDRHFRUWVKdVJfRktuRVpCeDFoUTVvaW9RMDktN2xLUHpkcjk=)

ENV_VARS: &ENV_VARS
    ENV_FILE_DEVELOP: .env.develop
    ENV_FILE_STAGING: .env.staging
    ENV_FILE_PRODUCTION: .env.production

workflows:
    react-native-staging:
        name: React Native App Staging
        environment:
            vars:
                << : [ *COMMON_VARS, *ENV_VARS ]
                ENV_SPECIFIC_FILE: $ENV_FILE_STAGING
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: staging
                  include: true
                  source: true
        scripts:   
            *scripts
            # - |
            #     # build iOS
            #     cd ios
            #     pod install
            #     xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
            # - name: App Center Build Distribution
            #   script: |
            #     #!/usr/bin/env zsh

            #     npm install -g appcenter-cli

            #     appcenter distribute release \
            #         --group "Staging builds" \
            #         --file "$FCI_BUILD_DIR/android/app/build/outputs/apk/release/app-release.apk" \
            #         --release-notes 'App submission via Codemagic' \
            #         --app aleksandr.termenzhy/TestProject \
            #         --token "${APP_CENTER_TOKEN}" \
            #         --quiet
        artifacts:
            - android/app/build/outputs/**/*.apk
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            slack:
                channel: '#test-app'
                notify_on_build_start: false
                notify:
                    success: true
                    failure: false

    react-native-production:
        name: React Native App Production
        environment:
            vars:
                << : [ *COMMON_VARS, *ENV_VARS ]
                ENV_SPECIFIC_FILE: $ENV_FILE_PRODUCTION
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: production
                  include: true
                  source: true
        scripts:
            *scripts
            # - |
            #     # build iOS
            #     cd ios
            #     pod install
            #     xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - android/app/build/outputs/**/*.apk
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            slack:
                channel: '#test-app'
                notify_on_build_start: false
                notify:
                    success: true
                    failure: false
