---

name: Pull request check

on:
  pull_request:
    branches: [production]

jobs:
  lint:
    name: Code lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Instal dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint
          
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: 'yarn'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.1.3
        with:
          gradle-version: 6.7
          build-root-directory: android
          gradle-executable: android/gradlew

      - name: Build gradle
        run: cd android && ./gradlew build
